### ISSUE TITLE
Bug with early stopping on loss

### ISSUE THREAD

**Issue by dfdazac** [abojchevski/graph2gauss#4]
Thanks for open sourcing your code!
This line:

https://github.com/abojchevski/graph2gauss/blob/2dbad876be291aad3198f2a8ba3d59740ec4e9e5/g2g/model.py#L262

is problematic for some datasets when training with `p_val = 0` and `p_test = 0` (as in the case of node classification), because the loss might start at values much higher than 1 and it might take more than 100 epochs to reach this value. This means that `self.__save_vars()` is never called, so then an exception is raised here:

https://github.com/abojchevski/graph2gauss/blob/2dbad876be291aad3198f2a8ba3d59740ec4e9e5/g2g/model.py#L299

because the attribute `self.saved_vars` does not exist. I worked around this by changing the first line above to 

```python
early_stopping_score_max = -float('inf')
```

**Comment by abojchevski** [comment]
Thanks for catching this! I've added the proposed change to the code.
