### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by fukien** [abojchevski/graph2gauss#5]
Hi, could you please show me how to get the dataset, thanks.

**Comment by abojchevski** [comment]
Which dataset are you referring to?

**Comment by fukien** [comment]
I am actually talking about how to convert the dataset to this *.npz format. For example, I can find the cora dataset at https://linqs.soe.ucsc.edu/data, but it's not the same format. Could you please tell me how to preprocess the dataset to the *.npz format, thanks.
